version: "3.4"

services:
  traefik_init:
    image: traefik:1.5
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=onurkeskindev@gmail.com"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=example.com"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - onke-net
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
  
  traefik:
    image: traefik:1.5
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - onke-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - onke-net

  user-service:
    image: user-service
    restart: always
    networks:
       - onke-net
       - default
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      - "traefik.backend=userservice"
      - "traefik.docker.network=onke-net"
      - "traefik.frontend.rule=Path:/grpc"
      - "traefik.enable=true"
      - "traefik.port=6767"
    environment:
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_PASS: ""
      DB_NAME: "CitadelAlliance"
      DB_PORT: "5432"
  
  users-api:
    image: user-service-api
    restart: always
    networks:
       - onke-net
       - default
    deploy:
      placement:
        constraints:
          - node.role == worker
    labels:
      - "traefik.docker.network=onke-net"
      - "traefik.enable=true"
      - "traefik.basic.frontend.path=Path:/api"
      - "traefik.basic.port=6767"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.path=Path:/admin-api"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=6767"

networks:
  onke-net:
    driver: overlay
  webgateway:
    driver: overlay
    external: true

volumes:
  consul-data:
      # driver: [not local]

# configs:
#   traefik-config:
#     file: config-letsencrypt.toml