// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUsersInfos(t *testing.T) {
	t.Parallel()

	query := UsersInfos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUsersInfosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsersInfosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UsersInfos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsersInfosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsersInfoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsersInfosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UsersInfoExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UsersInfo exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UsersInfoExists to return true, but got false.")
	}
}

func testUsersInfosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	usersInfoFound, err := FindUsersInfo(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if usersInfoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUsersInfosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UsersInfos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUsersInfosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UsersInfos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUsersInfosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	usersInfoOne := &UsersInfo{}
	usersInfoTwo := &UsersInfo{}
	if err = randomize.Struct(seed, usersInfoOne, usersInfoDBTypes, false, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}
	if err = randomize.Struct(seed, usersInfoTwo, usersInfoDBTypes, false, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usersInfoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usersInfoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsersInfos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUsersInfosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	usersInfoOne := &UsersInfo{}
	usersInfoTwo := &UsersInfo{}
	if err = randomize.Struct(seed, usersInfoOne, usersInfoDBTypes, false, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}
	if err = randomize.Struct(seed, usersInfoTwo, usersInfoDBTypes, false, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usersInfoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usersInfoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func usersInfoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func usersInfoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsersInfo) error {
	*o = UsersInfo{}
	return nil
}

func testUsersInfosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UsersInfo{}
	o := &UsersInfo{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, usersInfoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UsersInfo object: %s", err)
	}

	AddUsersInfoHook(boil.BeforeInsertHook, usersInfoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	usersInfoBeforeInsertHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.AfterInsertHook, usersInfoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	usersInfoAfterInsertHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.AfterSelectHook, usersInfoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	usersInfoAfterSelectHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.BeforeUpdateHook, usersInfoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	usersInfoBeforeUpdateHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.AfterUpdateHook, usersInfoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	usersInfoAfterUpdateHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.BeforeDeleteHook, usersInfoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	usersInfoBeforeDeleteHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.AfterDeleteHook, usersInfoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	usersInfoAfterDeleteHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.BeforeUpsertHook, usersInfoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	usersInfoBeforeUpsertHooks = []UsersInfoHook{}

	AddUsersInfoHook(boil.AfterUpsertHook, usersInfoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	usersInfoAfterUpsertHooks = []UsersInfoHook{}
}

func testUsersInfosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsersInfosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(usersInfoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsersInfoToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UsersInfo
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, usersInfoDBTypes, false, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := UsersInfoSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UsersInfo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUsersInfoToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsersInfo
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usersInfoDBTypes, false, strmangle.SetComplement(usersInfoPrimaryKeyColumns, usersInfoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UsersInfo != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUsersInfosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsersInfosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsersInfoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsersInfosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsersInfos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	usersInfoDBTypes = map[string]string{`CreatedDate`: `date`, `EmailPromotion`: `boolean`, `FirstName`: `character varying`, `ID`: `uuid`, `LastName`: `character varying`, `ModifiedDate`: `date`, `UserID`: `uuid`}
	_                = bytes.MinRead
)

func testUsersInfosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(usersInfoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(usersInfoColumns) == len(usersInfoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUsersInfosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(usersInfoColumns) == len(usersInfoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsersInfo{}
	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usersInfoDBTypes, true, usersInfoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(usersInfoColumns, usersInfoPrimaryKeyColumns) {
		fields = usersInfoColumns
	} else {
		fields = strmangle.SetComplement(
			usersInfoColumns,
			usersInfoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UsersInfoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUsersInfosUpsert(t *testing.T) {
	t.Parallel()

	if len(usersInfoColumns) == len(usersInfoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UsersInfo{}
	if err = randomize.Struct(seed, &o, usersInfoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsersInfo: %s", err)
	}

	count, err := UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, usersInfoDBTypes, false, usersInfoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsersInfo struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsersInfo: %s", err)
	}

	count, err = UsersInfos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
